In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("../dataset/student.csv")

In [4]:
data.head()

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42

In [5]:
data.shape

(100000, 18)

In [6]:
data.info

<bound method DataFrame.info of          branch college_tier  cgpa  backlogs  coding_skills  dsa_score  \
0           ECE       Tier-3  6.70         0            7.6        4.4
1      Chemical       Tier-2  5.70         0            5.4        7.9
2            EE       Tier-2  7.19         0            5.6        6.8
3            CE       Tier-2  6.48         0            5.2        3.1
4           CSE       Tier-2  6.71         1            5.9        4.7
...         ...          ...   ...       ...            ...        ...
99995        IT       Tier-3  6.08         0            3.1        5.4
99996        IT       Tier-3  7.46         0            4.8        6.8
99997        EE       Tier-2  7.94         0            4.9        9.1
99998        ME       Tier-3  6.63         0            5.0        8.0
99999       ECE       Tier-1  7.00         0            2.8        5.3

       aptitude_score  communication_skills  ml_knowledge  system_design  \
0                49.5                   3.7           6.4            0.3
1                72.0                   8.3           6.3            1.9
2                79.1                   7.4           4.4            5.2
3                48.4                   5.0           1.1            6.7
4                61.2                   4.3           2.7            2.8
...               ...                   ...           ...            ...
99995            67.4                   4.3           9.1            3.8
99996            59.5                   7.6           5.6            2.4
99997            55.1                   6.1           3.5            5.2
99998            65.0                   5.7           6.2            0.2
99999            64.5                   5.7           5.7            3.4

       internships  projects_count  certifications  hackathons  \
0                1               4               4           3
1                0               4               0           0
2                1               3               2           1
3                1               4               3           0
4                1               2               0           3
...            ...             ...             ...         ...
99995            2               3               2           0
99996            1               2               3           0
99997            0               2               1           0
99998            1               4               2           0
99999            0               2               2           2

       open_source_contributions  extracurriculars  placement_status  \
0                              2                 1                 1
1                              0                 0                 0
2                              2                 0                 1
3                              0                 0                 0
4                              0                 1                 1
...                          ...               ...               ...
99995                          0                 3                 0
99996                          1                 0                 1
99997                          1                 2                 1
99998                          0                 1                 1
99999                          0                 1                 1

       salary_package_lpa
0                   14.75
1                     NaN
2                   19.06
3                     NaN
4                   13.42
...                   ...
99995                 NaN
99996               16.58
99997               17.24
99998               17.01
99999               14.98

[100000 rows x 18 columns]>

In [7]:
data.describe()

,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,68475.000000
mean,7.206381,0.547010,5.995147,5.500711,64.990511,5.990614,4.508752,4.008210,1.095040,2.397280,1.49985,0.745840,0.450990,1.151100,0.684750,17.308014
std,0.925235,0.862727,1.496302,1.781961,11.990892,1.496552,1.968278,1.778405,0.940264,1.242829,1.11407,0.884189,0.671061,0.965162,0.464618,2.601041
min,4.000000,0.000000,1.000000,1.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,6.880000
25%,6.580000,0.000000,5.000000,4.300000,56.800000,5.000000,3.200000,2.800000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,15.530000
50%,7.210000,0.000000,6.000000,5.500000,65.000000,6.000000,4.500000,4.000000,1.000000,2.000000,1.00000,0.000000,0.000000,1.000000,1.000000,17.250000
75%,7.830000,1.000000,7.000000,6.700000,73.100000,7.000000,5.900000,5.200000,2.000000,3.000000,2.00000,1.000000,1.000000,2.000000,1.000000,19.040000
max,10.000000,3.000000,10.000000,10.000000,100.000000,10.000000,10.000000,10.000000,3.000000,5.000000,4.00000,3.000000,2.000000,3.000000,1.000000,28.330000

In [8]:
data.isnull().sum()

branch                           0
college_tier                     0
cgpa                             0
backlogs                         0
coding_skills                    0
dsa_score                        0
aptitude_score                   0
communication_skills             0
ml_knowledge                     0
system_design                    0
internships                      0
projects_count                   0
certifications                   0
hackathons                       0
open_source_contributions        0
extracurriculars                 0
placement_status                 0
salary_package_lpa           31525
dtype: int64

In [9]:
data['placement_status'].value_counts()

placement_status
1    68475
0    31525
Name: count, dtype: int64

In [10]:
#Let's use all the features first for classification model after preprocessing so that i can check their importance with the help of Randomforestclassifier and use it for best model that's selected among them.

In [11]:
data.duplicated().sum()

np.int64(0)

In [19]:
for col in data.columns:
    print(col, data[col].unique()[:5])

branch <ArrowStringArray>
['ECE', 'Chemical', 'EE', 'CE', 'CSE']
Length: 5, dtype: str
college_tier <ArrowStringArray>
['Tier-3', 'Tier-2', 'Tier-1']
Length: 3, dtype: str
cgpa [6.7  5.7  7.19 6.48 6.71]
backlogs [0 1 3 2]
coding_skills [7.6 5.4 5.6 5.2 5.9]
dsa_score [4.4 7.9 6.8 3.1 4.7]
aptitude_score [49.5 72.  79.1 48.4 61.2]
communication_skills [3.7 8.3 7.4 5.  4.3]
ml_knowledge [6.4 6.3 4.4 1.1 2.7]
system_design [0.3 1.9 5.2 6.7 2.8]
internships [1 0 2 3]
projects_count [4 3 2 5 1]
certifications [4 0 2 3 1]
hackathons [3 0 1 2]
open_source_contributions [2 0 1]
extracurriculars [1 0 3 2]
placement_status [1 0]
salary_package_lpa [14.75   nan 19.06 13.42 16.47]